<?php
pll_register_string('all-category', 'All Category', 'Global');
pll_register_string('booking-in-consultation', 'Book In A Consultation With Our Experts', 'Global');
pll_register_string('speak-to-an-expert', 'Speak To An Expert', 'Global');
pll_register_string('read-more', 'Read more', 'Global');
pll_register_string('our-certification', 'Our Certification', 'Global');
pll_register_string('company', 'Company', 'Global');
pll_register_string('our-services', 'Our Services', 'Global');
pll_register_string('resources', 'Resources', 'Global');
pll_register_string('trutedby-title', 'Trusted by leading <br/>businesses across the region', 'Global');
pll_register_string('trutedby-title-description', 'We are Source to Pay and Procure to Pay automation experts with over 30 years experience across our team and have been trusted partners to a number of leading organisations across APAC.', 'Global');
pll_register_string('source-to-pay', 'Source to Pay', 'Global');
pll_register_string('improve-goods-services-business', 'Improve goods/services business', 'Global');
pll_register_string('popular', 'Popular', 'Global');
pll_register_string('latest', 'Latest', 'Global');
pll_register_string('all-services', 'All services', 'Global');
pll_register_string('hometext', 'Home Text', 'Global');
pll_register_string('copyrightText', 'All Rights Reserved. Powered by', 'Global');
pll_register_string('data-not-found', 'Data Not Found', 'Global');
pll_register_string('our-service', 'Our Service', 'Global');
pll_register_string('eInvoicing', 'eInvoicing', 'Global');
pll_register_string('support-suppliers-and-buyers ', 'Support suppliers and buyers', 'Global');
pll_register_string('B2B-eCommerce', 'B2B eCommerce', 'Global');
pll_register_string('automating-buyer-and-supplier-trade ', 'Automating buyer and supplier trade', 'Global');
pll_register_string('trusted-by', 'Trusted By', 'Global');
pll_register_string('Resources', 'Resources', 'Global');
pll_register_string('news', 'News', 'Global');
pll_register_string('back-to-homepage', 'Back to homepage', 'Global');
pll_register_string('page-not-found', 'Page Not Found', 'Global');
pll_register_string('thank-message', 'The page you are looking for doesnt exist or has been moved', 'Global');
pll_register_string('read-more-news', 'Read more News', 'Global');
pll_register_string('expolore-news-related-to-valtatech', 'Expolore news related to valtatech', 'Global');
pll_register_string('case-studies', 'Case Studies', 'Global');
pll_register_string('explore-our-interesting-case-study', 'Explore our interesting case study', 'Global');
pll_register_string('our-technology-experience', 'Our Technology Experience', 'Global');
pll_register_string('what-our-customer-say', 'What our customer Say about us', 'Global');
pll_register_string('we-also-featured-in', 'We Also Featured In', 'Global');
pll_register_string('how-it-Works', 'How It Works', 'Global');
pll_register_string('key-benefits-for-you', 'Key Benefits for you', 'Global');
pll_register_string('key-benefits-for-your-customers', 'Key Benefits for your Customers', 'Global');
pll_register_string('thought-leadership', 'Thought Leadership', 'Thought Leadership');
pll_register_string('read-more-thought-leadership', 'Read More Thought Leadership', 'Thought Leadership');
pll_register_string('results', 'Results', 'Global');
pll_register_string('contact-us', 'Contact Us', 'Contact');
pll_register_string('case-study', 'Case Study', 'Case Study');
pll_register_string('read-more-about-our-work-with', 'Read More About Our Work With', 'Case Study');
pll_register_string('in-these-publications', 'In These Publications', 'Case Study');
